version: "3.4"

services:
  devcontainer:
    command: /bin/sh -c "while sleep 1000; do :; done"
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../:/workspace:cached
      - ${SSH_DIR}:/root/.ssh/:rw
      - ${GIT_CONF}:/root/.gitconfig
      - ${M2_DIR}:/root/.m2:rw
